### ISSUE TITLE
Phase out codicons

### ISSUE THREAD

**Issue by poly2it** [wroyca/vscode-rounded#13]
codicons should be phased out in favor of Adwaita ([CC-BY-CA 3 + LGPL v3](https://github.com/GNOME/adwaita-icon-theme/blob/master/COPYING)) and GNOME Builder ([GPL v3](https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/main/COPYING)) icons. Icons overwritten by this theme would apply to all interfaces as well as extensions using codicons.
For a full list of codicons, see: https://microsoft.github.io/vscode-codicons/dist/codicon.html.

The question is; how should the icons be implemented?

One method which could work is recoloring the icons to white, then [baking the SVG icons into CSS URLs](https://yoksel.github.io/url-encoder/). Icons can then be replaced gradually.
```css

.monaco-workbench .codicon[class*=codicon-] {
  width: 16px;
  height: 16px;
}

.codicon-terminal:before {
  content: url("...");
}
```

![Screenshot from 2023-05-18 20-29-12](https://github.com/wroyca/libadwaita-vscode-theme/assets/84731064/56e1bcaa-5682-40e7-9e5d-4b2c4b2f2efc)
